name: ci-cd pipeline workflow-5

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Configuration
        run: echo "Setting up configuration"

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting Up Node Version
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install

      - name: Test script run
        run: |
         npm test
         echo "Test completed"


  build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup node version
          uses: actions/setup-node@v4
          with:
            node-version: "20"

        - name: Install Dependencies
          run: npm install

        - name: Make Build
          run: npm run build

        - name: Upload Build Folder
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: ./dist

        - name: Upload Conformation
          run: echo "Upload build completed"
