name: ci-cd pipeline workflow-5

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Configuration
        run: echo "Setting up configuration"

  setup-notify:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Setup Success notification
        run: |
          if [ -d "node_modules" ]; then
            echo "Dependencies installed"
          else
            echo "Dependencies missing"
          fi


  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting Up Node Version
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing Dependencies
        run: npm install

      - name: Test script run
        run: |
         npm test
         echo "Test completed"


  build:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup node version
          uses: actions/setup-node@v4
          with:
            node-version: "20"

        - name: Install Dependencies
          run: npm install

        - name: Make Build
          run: npm run build

        - name: Upload Build Folder
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: ./dist

        - name: Upload Conformation
          run: echo "Upload build completed"

  build-notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Success notification
        run: |
          if [ -d "dist" ]; then
            echo "Build completed successfully"
          else
            echo "Build failed: 'dist' folder not found"
          fi





  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Node -v setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Download build folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .dist

      - name: Install netlify cli
        run: npm install -g netlify-cli

      - name: Deploy to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        run: |
             netlify deploy --dir=./dist --site=$NETLIFY_SITE_ID --prod

      - name: Deployment done
        run: echo "✅ Deployment to Netlify completed!"
