name: ci-cd pipeline workflow-5

on:
  push:
    branches:
      - main
  paths-ignore:
    - ".github/workflows"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup configuration
        run: echo "Setting up configuration"
